### ISSUE TITLE
求相关文献

### ISSUE THREAD

**Issue by ACPMMD** [tim5go/zhopenie#2]
请问你的程序算法有发表过相关论文，或者是根据哪篇论文复现的吗？求相关文献阅读？

**Comment by tim5go** [comment]
@cuipi254645734 

**Chinese Open Relation Extraction for Knowledge Acquisition**
http://aclweb.org/anthology/E14-4003

**Identifying Relations for Open Information Extraction**
http://www.aclweb.org/anthology/D11-1142

Hope this helps ^^

**Comment by ACPMMD** [comment]
非常感谢！

**Comment by ACPMMD** [comment]
你们用的是繁体的语料吗？

**Comment by tim5go** [comment]
The semantic model of **Language Technology Platform** is based on Simplified Chinese. In my example code, the input is Traditional Chinese, that's why I needed to convert my text into Simplified Chinese first before feeding into the LTP semantic model. For your case, you can simply skip the conversion part. ^^
